//
// Created by kwitnoncy on 12.05.2021.
//

#ifndef PUTM_EV_CAN_TRANSLATOR_F105_TRACTIVE_SYSTEM_META_H
#define PUTM_EV_CAN_TRANSLATOR_F105_TRACTIVE_SYSTEM_META_H

#define TS_MESS_ID      0x00
#define TS_MESS_BYTE    0x00
#define TS_MESS_BIT     0x00

#endif //PUTM_EV_CAN_TRANSLATOR_F105_TRACTIVE_SYSTEM_META_H
